import Header from "@/components/Header";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        <title>Imbb clone</title>
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <meta content="Imdb clone application" name="description" />
      </head>
      <body>

        <Header />

        {children}
      
      </body>
    </html>
  );
}
